sudo: false

install:
  - wget https://www.mirrorservice.org/sites/ftp.cs.vu.nl/pub/minix/distfiles/backup/acme091src.tar.gz
  - tar xzf acme091src.tar.gz
  - make -C acme091/src install BINDIR=$PWD/acme-bin
  - export PATH=$PATH:$PWD/acme-bin

language: python

script:
  - python tests.py
  - python tools/test_imageutil.py
  - python tools/makeboot.py 5 "`mktemp`.img"
  - python tools/makeboot.py 8 "`mktemp`.img"
